### ISSUE TITLE
About the code and pretrained models

### ISSUE THREAD

**Issue by zinuoli** [fengzhang427/LLF-LUT#1]
Dear authors, it's a great work! May I know when will you release your code?

**Comment by fengzhang427** [comment]
Really appreciate your interest in our work. However, since this work is already applied to the products, I am still negotiating with the company to get the approval to release the source code as soon as possible.

**Comment by zinuoli** [comment]
Thank you for your reply, hope it will be released soon. Have a good day :)

**Comment by fengzhang427** [comment]
> ??? Soon is how soon

We apologize for the long delay. Due to corporate reasons, we are unable to release the code of NeurIPS version, we will release the code of TPAMI version in May.

**Comment by zinuoli** [comment]
> > ??? Soon is how soon
> 
> We apologize for the long delay. Due to corporate reasons, we are unable to release the code of NeurIPS version, we will release the code of TPAMI version in May.

I understand due to some copyright issues the code may not be able to be realeased. By the way, when will you release your TPAMI version paper on arxiv?

**Comment by fengzhang427** [comment]
We have completed the experiments; however, the paper is not yet finalized. Therefore, it will likely not be released on arXiv until the end of May.

**Comment by yx-chan131** [comment]
@fengzhang427 Hi, could you share the paper/code link of TPAMI version? Thanks!
